import { describe, it, expect, vi, beforeEach } from 'vitest';
import { GenerateNoteDraftUseCase } from '../GenerateNoteDraftUseCase';
import { createMockAiService } from '../../../tests/setup/mockRepositories';

describe('GenerateNoteDraftUseCase', () => {
  let mockAiService: ReturnType<typeof createMockAiService>;
  let useCase: GenerateNoteDraftUseCase;

  beforeEach(() => {
    vi.clearAllMocks();
    mockAiService = createMockAiService();
    useCase = new GenerateNoteDraftUseCase(mockAiService);
  });

  it('successfully generates draft content using the AiService', async () => {
    const mockHtmlResponse = '<h2>Draft generated by AI</h2><p>About React...</p>';
    vi.mocked(mockAiService.generateNoteContent).mockResolvedValue(mockHtmlResponse);

    const result = await useCase.execute({ topic: 'React Hooks' });

    expect(mockAiService.generateNoteContent).toHaveBeenCalledWith('React Hooks');
    expect(result.generatedContent).toBe(mockHtmlResponse);
  });
  
  it('allows the error to bubble up if the AiService fails (e.g. Rate Limit or API down)', async () => {
    vi.mocked(mockAiService.generateNoteContent).mockRejectedValue(new Error('API límite excedido'));

    await expect(useCase.execute({ topic: 'Cualquier cosa' }))
      .rejects.toThrowError('API límite excedido');
  });
});