### 0. Obtener Token de Desarrollo
GET http://localhost:3000/api/auth/dev-token

### 1. Crear una Nueva Nota
POST http://localhost:3000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyLWRlbW8tMDAxIiwiaWF0IjoxNzcyNzg1MTYyLCJleHAiOjE3NzI3ODg3NjJ9.qdzXuchigGeUll-1BQ_ENFzvBy5pNy8OUbU2dNEbZzg

{
  "title": "Nota autenticada",
  "content": "Esta nota pasó por Zod, por el JWT, y se guardó en MongoDB.",
  "tags": ["seguridad"]
}

### 2. Auto-etiquetar con Gemini AI
POST http://localhost:3000/api/notes/58698f31-c4f6-436e-b2db-5d172910ef15/tags


### 3. Prueba de Seguridad (tiene que fallar por Zod)
POST http://localhost:3000/api/notes
Content-Type: application/json

{
  "userId": 12345, 
  "content": ""
}