import type { IAiService } from '@domain/ports/IAiService';

interface Input {
  topic: string;
}

interface Output {
  generatedContent: string;
}


/* Use case: Retrieve a draft generated by the aiService  */

export class GenerateNoteDraftUseCase {
  constructor(private readonly aiService: IAiService) {}

  async execute(input: Input): Promise<Output> {
    return { generatedContent: await this.aiService.generateNoteContent(input.topic) };
  }
}
